name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every hour
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: BlaCkinkGJ/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      - uses: lowlighter/metrics@latest
        with:
          # ... other options
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_contributors: yes
          plugin_contributors_base: ""               # Base reference (commit, tag, branch, etc.)
          plugin_contributors_head: main             # Head reference (commit, tag, branch, etc.)
          plugin_contributors_ignored: bot           # Ignore "bot" user
          plugin_contributors_contributions: yes     # Display number of contributions for each contributor
          plugin_contributors_sections: contributors # Display contributors sections
